### ISSUE TITLE
关于channel_gcn

### ISSUE THREAD

**Issue by bianwk** [muzishen/HPGN#2]
您好，遇到以下问题
File "C:\Users\20201\Desktop\HPGN-main\network.py", line 304, in __init__
    self.channel_gcn = channel_gcn(2048,1024)
NameError: name 'channel_gcn' is not defined
在代码里没有见到这个模块的定义，请问可以提供吗

**Comment by muzishen** [comment]
这是个bug，直接注释掉就行。

**Comment by bianwk** [comment]
非常感谢

**Comment by bianwk** [comment]
作者大大您好，还有一个问题是权重文件已经失效了，请问能再发一次吗求求了
